# =========================
# Application
# =========================
spring.application.name=urbansync-backend
server.port=8080
spring.jpa.open-in-view=false

# =========================
# PostgreSQL
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# Hibernate / JPA
# =========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# =========================
# Logging
# =========================
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN

# =========================
# Razorpay
# =========================
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# =========================
# Brevo Email API
# =========================
BREVO_API_KEY=${BREVO_API_KEY}